# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8303ca32d96da77f7ace7c3ff62d8cab6a25335b45e3bafe9b7d6544da3462e3e859816f1b6d0e68cb67f2d1c9b7fcfe0237d194fffdc51090e15fcae6eebc39

test:
  secret_key_base: 53de76d6c61c625ba869a6ab362e2d084359efd9315e4056ae52a16c9c59fb555ecf8411a52b690247e6d9b176c67f3a977fb808b3255f5e739581869f0fc5bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
